## 代数运算

In [ ]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]],np.int32)
print(type(x))
print(x.shape)
print(x.dtype)

In [5]:
# The element of x in the *second* row, *third* column, namely, 6.
# start with zero:0
x[1,2]

6

In [7]:
y = x[:,1]
print(y)
y[0] = 9
print(y)
print(x)

[2 5]
[9 5]
[[1 9 3]
 [4 5 6]]


## 矩阵运算

### 逆矩阵
matrix inverse 
- 定义$AA^{-1} = I$
- 要求是只能方阵
 

In [6]:
import numpy as np
from numpy.linalg import inv
x = np.array([[1,2],[3,4]],np.int32)
inv(x)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### 矩阵转置
transpose:$A^T$
(i,j) => (j,i)

In [7]:
x = np.array([[1,2],[3,4]],np.int32)
x.transpose()

array([[1, 3],
       [2, 4]], dtype=int32)

## 概率统计

In [9]:
x = np.array([[1,2],[3,4]],np.int32)

## mean
print(x.mean())

## var
print(x.var())

2.5
1.25
